### ISSUE TITLE
Trying to use this

### ISSUE THREAD

**Issue by edgarecayce** [ennerperez/RibbonLib#1]
I have a project I am trying to get working created by someone who used the original RibbonLib.  I am able to get your code installed and working from NuGet, but I run into some issues. 

1) They used an XML file called Ribbon.XML but this uses RibbonMarkup.XML.  No worries, I just rename the file.
2) They have a "SplitButton" tag that gets me this error in build: warning SC2001: Undefined Command on element.
3) I get many errors in code
            <Ribbon.SizeDefinitions>
                <SizeDefinition Name="sizeDefGrpParagraph">
warning SC1000: An invalid 'IsImageVisible' configuration has been found in the size definition 'sizeDefGrpParagraph'. A control in a smaller layout cannot have a size larger than that of the same control in a larger layout.

Any ideas?

Thanks

**Comment by edgarecayce** [comment]
hmm this strips out my tags.  Its Ribbon.SizeDefinitions and then SizeDefinition Name="sizeDefGrpParagraph"

**Comment by ennerperez** [comment]
Let me know any progress
